exclude: ^diff/
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
      files: ^module/.*(\.tf|\.tfvars)$
    - id: terraform_tflint
    - id: terraform_docs_replace
      files: ^module/.*(\.tf|\.tfvars)$
      args: ['--with-aggregate-type-defaults']
