name: Release command diff

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.17.0'
      - name: Install dependencies
        run: |
          go version
          go install golang.org/x/lint/golint@latest
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
          workdir: ./diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
